### PR TITLE
Parenthesize a first spread element when necessary

### LINKED ISSUE #177: Array spread breaks ternaries due to not parenthesising them
[**Minimal test case:**](https://buble.surge.sh/#%5B...a%20%3F%20b%20%3A%20c%2C%20d%5D)

```js
[...a ? b : c, d]
```

**Result:**

```js
a ? b : c.concat( [d])
```

**Expected:**

```js
(a ? b : c).concat( [d])
```

These two are *wildly* different!

The **workaround** is manual parenthesisation:

```js
[...(a ? b : c), d]
```

Given that you can only spread iterables in array spread, I think ternaries are the only realistic situation where this will matter. (Well, I guess strings could wreck it too—`...a + b`—but #166 shows spreading strings is broken anyway.)

### PR DESCRIPTION
**Pull request by chris-morgan**
In most cases this is unnecessary, but for some expression types it is necessary, notably in ternaries; for `a ? b : c.concat(…)` is very different from `(a ? b : c).concat(…)`.

I’m not clear why the insertion of the opening parenthesis had to happen in src/program/types/CallExpression.js rather than src/utils/spread.js when start === element.start; but if I did it inside spread(), if I used appendLeft or prependLeft it’d end up like `.apply((Math, a).concat(…))` instead of `.apply(Math, (a).concat(…))`, and if I used appendRight or prependRight, nothing happened.

Fixes #177.

### CODE REVIEW

File: src/utils/spread.js [hunk 1]
```diff
@@ -47,8 +47,13 @@ export default function spread(
...
 
 	if (!previousElement) {
-		code.remove(start, element.start);
-		code.overwrite(element.end, elements[1].start, '.concat( ');
+		// We parenthesize it to handle ternaries like [...a ? b : c].
+		// (We could be smarter about it, but with the parenthesizing having
+		// spread to CallExpression.js, it sounds too much like hard work.)
+		if (start !== element.start) {
+			code.overwrite(start, element.start, '( ');
+		} // else CallExpression called us, and it puts the ( in itself.
```
Comment (nathancahill) [inline src/utils/spread.js]: Slightly concerned that the `start !== element.start` might not be robust/explicit enough to match the code paths in `CallExpression` that add the opening parens. Would a parent check be better here?

Comment (chris-morgan) [reply src/utils/spread.js]: Seems a reasonable concern. I’ve added another commit with what I imagine you would like there. (I’d amend the first commit, but then GitHub doesn’t show a proper diff.)

**Comment by adrianheine** [comment]
Thanks! Would it be possible to at least catch the simplest and most common case of a single spreaded identifier?

**Comment by chris-morgan** [comment]
You, and what I ended up with in #179, inspired me to extract the test into another function that can be called from both spread.js and CallExpression.js. The end result is that I’ve whitelisted Identifier, CallExpression and a few other types that definitely don’t need parentheses.

Rebased on top of master too (conflicted with #179 as both added functions and tests in the same places).

Not squashed for review purposes, although I normally would (the three commits deserve to be one).

**Comment by adrianheine** [comment]
Nice! Do you want to squash the commits yourself?

**Comment by chris-morgan** [comment]
Squashed with the proper commit message. When the tests pass, I’m ready for it to be merged.

**Comment by adrianheine** [comment]
Thanks!
